### ISSUE TITLE
error: Can't run the code.

### ISSUE THREAD

**Issue by sbmaruf** [dipta007/spoj-code-downloader#1]
System: Ubuntu 16.04
error message:

> Traceback (most recent call last):
>   File "/home/sbmaruf/anaconda3/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
>     stdin=PIPE)
>   File "/home/sbmaruf/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
>     restore_signals, start_new_session)
>   File "/home/sbmaruf/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> PermissionError: [Errno 13] Permission denied: '/home/sbmaruf/Documents/spoj-code-downloader/chromedriver_linux'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "spoj-downloader.py", line 38, in <module>
>     driver = webdriver.Chrome(GetPathOfChromeDriver())
>   File "/home/sbmaruf/anaconda3/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
>     self.service.start()
>   File "/home/sbmaruf/anaconda3/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 88, in start
>     os.path.basename(self.path), self.start_error_message)
> selenium.common.exceptions.WebDriverException: Message: 'chromedriver_linux' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by dipta007** [comment]
I think you have to give permission to the linux driver from terminal
1. open the terminal
2. Go to the folder
3. Run this command
```
sudo chmod 777 chromedriver_linux
```
4. Then run the script

I think it will solve the issue

**Comment by sbmaruf** [comment]
Hi ... Thanks for the fast reply.

> Traceback (most recent call last):
>   File "spoj-downloader.py", line 38, in <module>
>     driver = webdriver.Chrome(GetPathOfChromeDriver())
>   File "/home/sbmaruf/anaconda3/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
>     self.service.start()
>   File "/home/sbmaruf/anaconda3/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
>     stdin=PIPE)
>   File "/home/sbmaruf/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
>     restore_signals, start_new_session)
>   File "/home/sbmaruf/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> OSError: [Errno 8] Exec format error: '/home/sbmaruf/Documents/spoj-code-downloader/chromedriver_linux'

Here's the new error.

**Comment by dipta007** [comment]
there was a problem with the versioning of chromedriver. Updated the repo.

**Comment by sbmaruf** [comment]
Now it's working. :)

**Comment by dipta007** [comment]
😄 😄
